# Generated by Django 6.0.6 on 2026-10-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
    ]
