# Generated by Django 6.0.6 on 2026-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_remove_note_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background',
            field=models.CharField(choices=[('none', 'None'), ('sage', 'Sage mist'), ('rose', 'Rose sand'), ('dusk', 'Dusk'), ('ocean', 'Ocean'), ('sunlit', 'Sunlit'), ('midnight', 'Midnight')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='template',
            field=models.CharField(choices=[('plain', 'Plain'), ('quote', 'Quote')], default='plain', max_length=10),
        ),
    ]
